Search movies
WoytekMig/movies-browser pull request #34
Opened 2023-09-15 15:15 UTC by WoytekMig

changed component from searching people to search either people or movies. Added loading screen during fetching data from api and changed title during loading data :)

2023-09-15 17:24 UTC, KrystianZybura requested changes
Nice job! Sadly there is an error, when we try to search for Movies way too fast meanwhile loading due to missing data for MovieTile. It occurs only when, we use the navigation from People to Movies and using search during the loading phase.
![image](https://github.com/WoytekMig/movies-browser/assets/121553175/91b727fc-23b0-4f67-94b6-5d3920fd8142)


Other than that, the search doesn't work on Profile and Movie Page as we discussed earlier, it should be fixed before merge.

2023-09-15 17:24 UTC, KrystianZybura commented on src/features/MoviesBrowser/SearchResult/index.js
>        />
Isn't it a bit too complicated?

2023-09-17 20:28 UTC, Arcziwald approved these changes
Good job :-)

2023-09-17 20:32 UTC, KrystianZybura approved these changes
Nice job, works well 👌

2023-09-17 21:16 UTC, merged